#!/bin/bash -
#
# Binary Decomposition Script
# author: Anton Hibl

# Create Folder to hold decomposition
mkdir $1_decomp

# File 1
 # Assembly
gcc -S $1.c -o $1_decomp/asm_$1.s
 # Pre-processing and Directives
gcc -E -P $1.c -o $1_decomp/prcsr_$1.p

# If File 2 is provided
if [ "$2" ]
then
    # Assembly
    gcc -S $2.c -o $1_decomp/asm_$2.s
    # Pre-processing and Directives
    gcc -E -P $2.c -o $1_decomp/prcsr_$2.p
fi

# If File 3 is provided
if [ "$3" ]
then
    # Assembly
    gcc -S $3.c -o $1_decomp/asm_$3.s
    # Pre-processing and Directives
    gcc -E -P $3.c -o $1_decomp/prcsr_$3.p
fi

# Link assembly into ELF executable format
 # If File 2 exists
if [ "$2" ]
then
    # If File 3 exists
    if [ "$3" ]
    then
	# Link and assemble all 3 files into an ELF executable
        gcc -Wall -Werror -Wextra $1_decomp/asm_$1.s $1_decomp/asm_$2.s $1_decomp/asm_$3.s -o $1_decomp/$1bin -lm
    else
        # Link and assemble both file into an ELF executable
        gcc -Wall -Werror -Wextra $1_decomp/asm_$1.s $1_decomp/asm_$2.s -o $1_decomp/$1bin -lm
    fi
else
    # Otherwise link only the first file
    gcc -Wall -Werror -Wextra $1_decomp/asm_$1.s -o $1_decomp/$1bin -lm
fi

# Create a copy of the binary executable
cp $1_decomp/$1bin $1_decomp/$1strippedbin

# Strip the copy of all irrelevant symbols
strip $1_decomp/$1strippedbin
