#!/bin/sh

# Encryption Program

if [ "$1" == "-e" ]
then
	base64 $2 | rot13 > $2.bot
elif [ "$1" == "-d" ]
then
	filename=$(echo "$2" | sed 's/.bot//g')
	rot13 $2 | base64 -D > $filename
elif [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "" ]
then
  echo "BOT18 Encryption CLI Tool"
  echo "Usage: 'bot18 [FLAG] input_filepath'"
  echo "Parameters:"
  echo "             FLAG :: '-d' -> decrypt and '-e' -> encrypt"
  echo "   input_filepath :: path for file to encrypt or decrypt"
else
	base64 $1 | rot13
fi

