#!/bin/bash -

# rsync File Transfer Script
# author: Anton Hibl

echo Enter a filepath:

read downloadpath

echo Enter the Output Path:

read outputpath

echo

# Download file from server using rsync
rsync -zh -e 'ssh -i ~/.ssh/id_ed25519' -P aeh436@35.84.205.21:$downloadpath $outputpath
