#!/bin/bash -

# rsync File Transfer Script
# author: Anton Hibl

echo Enter the login account:

read login_account

echo Enter the IP address:

read ip_address

echo Enter a filepath:

read downloadpath

echo Enter the Output Path:

read outputpath

echo

# Download file from server using rsync
rsync -zh -e 'ssh -P $login_account@$ip_address:$downloadpath $outputpath'
