#!/bin/sh

# ROT13 Encryption Program
# Author Anton Hibl

if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
	echo "ROT13 Encryption CLI Tool"
	echo "Usage: rot13 [FLAG] input_file"
	echo " --help/-h :: Displays this message"
else
	cat $1 | tr '[A-Za-z]' '[N-ZA-Mn-za-m]'
fi
